baseURL = 'https://betsyhcamp.github.io/'
languageCode = 'en-us'
title = 'Elizabeth H. Camp'
theme = 'PaperMod'
enableEmoji = true

[params]
title = "A basic personal static  website"
author = "Elizabeth H. Camp"
description = "Static website of Elizabeth H. Camp"
